#!/bin/sh -e

#DEBHELPER#

if [ "$1" = "purge" ]
then
  rm -rf /etc/ssh
fi

if [ "$1" = "purge" ] ; then
    update-rc.d ssh remove >/dev/null
fi

if [ "$1" = "purge" ] ; then
	deluser --quiet sshd > /dev/null || true
	delgroup --quiet ssh > /dev/null || true
fi

exit 0
